- name: Update and Upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install basic software
  apt:
    name:
      - git
      - curl
      - ufw
      - ca-certificates
      - ncdu
      - tmux
    state: present
